
<h1><?php echo $this->translate('Menus overzicht');?></h1>

<ul>
    <li><a href="/admin/menu/toevoegen"><?php echo $this->translate('Toevoegen');?></a></li>    
</ul>
<?php foreach ($this->menus as $menu) { ?>
    <p><?php echo $menu['slug'];?> 
        <a href='/admin/menu/wijzigen/id/<?php echo $menu['menuId']; ?>'><?php $this->translate('Wijzig');?></a>
        <a href='/admin/menu/verwijderen/id/<?php echo $menu['menuId'];?>'><?php $this->translate('Verwijder');?></a>
    </p>
    <hr/>
<?php }

