<?php 
$this->placeholder('mainTitle')->set('Dealer-Module : Product');

$module = 'dealer';
$controller = 'product';
?>
 <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'add'),NULL,TRUE); ?>">
    <img src="/base/images/icons/create.png">
</a>
<table>
    <tr>
        <th><?php echo $this->translate('lbl_label');?></th>
        <th><?php echo $this->translate('lbl_price');?></th>
        <th><?php echo $this->translate('lbl_highlight');?></th>
    </tr>
<?php if($this->rows) { ?>
<?php   foreach($this->rows as $row) { ?>
            <tr>
                <td><?php echo isset($row['locale']) ? $row['locale']['title'] : $row['label'];?></td>
                <td><?php echo $row['price']?></td>
                <td><?php echo $row['highlight']?></td>
                <td>
                    <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'change', 'productId' => $row['productId']),NULL,TRUE); ?>">
                        <img src="/base/images/icons/edit.png">
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'delete', 'productId' => $row['productId']),NULL,TRUE); ?>" onclick="return confirm('<?php echo $this->translate('lbl_delete'); ?>?')">
                        <img src="/base/images/icons/cross.png">
                    </a>
                </td>
            </tr>
<?php   } ?>            

<?php } else $this->translate('lbl_emptytable'); ?>
</table>

