<?php 
$this->placeholder('mainTitle')->set('Admin-Menu');

$module = 'admin';
$controller = 'menu';
?>
 <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'add'),NULL,TRUE); ?>">
    <img src="/base/images/icons/create.png">
</a>
<table>
    <tr>
        <th><?php echo $this->translate('lbl_label');?></th>
        <th><?php echo $this->translate('lbl_module');?></th>
        <th><?php echo $this->translate('lbl_controller');?></th>
        <th><?php echo $this->translate('lbl_action');?></th>
        <th><?php echo $this->translate('lbl_slug');?></th>
        <th><?php echo $this->translate('lbl_status');?></th>
    </tr>
<?php if($this->rows) { ?>
<?php   foreach($this->rows as $row) { ?>
            <tr>
                <td><?php echo $row['label']?></td>
                <td><?php echo $row['module']?></td>
                <td><?php echo $row['controller']?></td>
                <td><?php echo $row['action']?></td>
                <td><?php echo $row['slug']?></td>
                <td><?php echo $row['status']?></td>
                <td>
                    <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'change', 'menuId' => $row['menuId']),NULL,TRUE); ?>">
                        <img src="/base/images/icons/edit.png">
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'delete', 'menuId' => $row['menuId']),NULL,TRUE); ?>" onclick="return confirm('<?php echo $this->translate('lbl_delete'); ?>?')">
                        <img src="/base/images/icons/cross.png">
                    </a>
                </td>
            </tr>
<?php   } ?>            

<?php } else $this->translate('lbl_emptytable'); ?>
</table>
