<?php 
$this->placeholder('mainTitle')->set('User-Module : Order');

$module = 'user';
$controller = 'order';
if($this->authUserRow['roleId']>2) { ?>  
    <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'add'),NULL,TRUE); ?>">
        <img src="/base/images/icons/create.png">
    </a>
<?php } ?>
<table>
    <tr>
        <th><?php echo $this->translate('lbl_order');?></th>
        <th><?php echo $this->translate('lbl_user');?></th>
        <th><?php echo $this->translate('lbl_reference');?></th>
    </tr>
<?php if($this->rows) { 
        foreach($this->rows as $row) { ?>
            <tr>
                <td><?php echo $row['orderId']?></td>
                <td><?php echo $row['userId']?></td>
                <td><?php echo $row['reference']?></td>
<?php           if($this->authUser['roleId']>2) { ?>                
                    <td>
                        <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'change', 'orderId' => $row['orderId']),NULL,TRUE); ?>">
                            <img src="/base/images/icons/edit.png">
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'delete', 'orderId' => $row['orderId']),NULL,TRUE); ?>" onclick="return confirm('<?php echo $this->translate('lbl_delete'); ?>?')">
                            <img src="/base/images/icons/cross.png">
                        </a>
                    </td>
<?php           } ?>                         
                <td>
                    <a href="<?php echo $this->url(array('module'=> $module,'controller' => 'Orderdetail', 'action' => 'listbyorder', 'orderId' => $row['orderId']),NULL,TRUE); ?>">
                        <?php echo $this->translate('lbl_details');?>
                    </a>
                </td>
               
            </tr>
<?php   } ?>            

<?php } else $this->translate('lbl_emptytable'); ?>            
</table>

