<?php 
$this->placeholder('mainTitle')->set($this->translate('lbl_basket'));

$module = 'default';
$controller = 'basket';
?>
 <table>
    <tr>
        <th><?php echo $this->translate('lbl_product');?></th>
        <th><?php echo $this->translate('lbl_quantity');?></th>
    </tr>
<?php if($this->rows) { ?>
<?php   foreach($this->rows as $row) { ?>
            <tr>
                <td><?php echo $row['title'] ? $row['title'] : $row['label']?></td>
                <td><?php echo $row['quantity']?></td>
                <td>
                    <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'change', 'basketId' => $row['basketId']),NULL,TRUE); ?>">
                        <img src="/base/images/icons/edit.png">
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'delete', 'basketId' => $row['basketId']),NULL,TRUE); ?>" onclick="return confirm('<?php echo $this->translate('lbl_delete'); ?>?')">
                        <img src="/base/images/icons/cross.png">
                    </a>
                </td>
            </tr>
<?php   } ?>            

<?php } else $this->translate('lbl_emptytable'); ?>            
</table>

