<!doctype html>
<html>
    <head>
        <title>ZF Shop</title>
        <link href="/css/style.css" rel="stylesheet" />
        <meta charset="UTF-8" />
    </head>
    <body class="normalpage">
        <section id="page">
            <div id="bodywrap">
                <section id="top">
                    <nav>
                        <h1 id="sitename">
                            <a href="#">Portfolio | Premium CSS Template </a>
                        </h1>
                        <?php echo $this->navigation()->menu(); ?>
                    </nav>
<?php               foreach($this->locales as $locale) { ?>
                        <a href="<?php echo $this->url(array('controller' => 'index','action' => 'index','lang' => $locale['locale']),NULL,TRUE);?>" 
                           style="font-size:150%;color:gray">
                               <?php echo $locale['short'];?>
                        </a> |
<?php               } ?>
                    
                </section>
                <section id="container">
                    <div id="contents">
                        <header>
                            <div id="right">
                                <div id="login">
                                    <span style="float:right">
                                        <?php echo $this->signupForm($this->signupForm); ?>
                                    </span>
                                </div><hr />
                                <div id="basket">
                                    <span style="float:left">
<?php                                       if($this->basket) { ?>
                                                <h1>Winkelmand</h1>
                                                <table id="tbl_basket">
                                                    <tr>
                                                        <th>Naam</th>
                                                        <th>Prijs</th>
                                                        <th>Aantal</th>
                                                    </tr>
<?php                                               foreach($this->basket as $basket) { ?>
                                                        <tr>
                                                            <td class="td_basket"><?= $basket['label'];?></td>
                                                            <td class="td_basket"><?= $basket['price'];?></td>
                                                            <td class="td_basket"><?= $basket['quantity'];?></td>
                                                        </tr>
<?php                                               } ?>
                                                </table>
<?php                                       } ?>
                                    </span>
                                </div>
                            </div>
                        </header>
                        <section id="content">
                            <?php echo $this->layout()->content; ?>
                        </section>

                        <footer>Footer</footer>
                        <br class="clear" />
                    </div>
                </section>
            </div>
        </section>
    </body>
</html>