<!doctype html>
<html>
    <head>
        <title>ZF Shop</title>
        <link href="/css/style.css" rel="stylesheet" />
        <meta charset="UTF-8" />
<?php
            echo $this->jQuery().PHP_EOL;
            echo $this->headScript();
        ?>
        
    </head>
    <body class="normalpage">
        <section id="page">
            <div id="bodywrap">
                <section id="top">
                    <nav>
                        <h1 id="sitename">
                            <a href="#">Portfolio | Premium CSS Template </a>
                        </h1>
                        <?php echo $this->navigation()->menu();?>

                    </nav>
<?php               foreach($this->locales as $locale) { ?>
                        <a href="<?php echo $this->url(array('controller' => 'index','action' => 'index','lang' => $locale['locale']),NULL,TRUE);?>" 
                           style="font-size:150%;color:gray">
                               <?php echo $locale['short'];?>
                        </a> |
<?php               } ?>
                    
                </section>
                <section id="container">
                    <section id="contents">
                        <header>
                            <section id="rightSection">
                                <article id="searchArticle">
                                    <span style="float:right">
                                        <?php echo $this->searchForm($this->searchForm); ?>
                                    </span>
                                </article>
                                <article id="loginArticle">
                                    <span>
                                        <?php echo $this->signupForm($this->signupForm); ?>
                                    </span>
                                </article>

                                <article id="basketArticle">
                                    <span>
<?php                                       if($this->basket) { ?>
                                                <h1><?php echo $this->translate('lbl_basket');?></h1>
                                                <table id="tbl_basket">
                                                    <tr>
                                                        <th><?php echo $this->translate('lbl_name');?></th>
                                                        <th><?php echo $this->translate('lbl_price');?></th>
                                                        <th><?php echo $this->translate('lbl_quantity');?></th>
                                                    </tr>
<?php                                               foreach($this->basket as $basket) { ?>
                                                        <tr>
                                                            <td class="td_basket"><?= $basket['label'];?></td>
                                                            <td class="td_basket"><?= $basket['price'];?></td>
                                                            <td class="td_basket"><?= $basket['quantity'];?></td>
                                                        </tr>
<?php                                               } ?>
                                                </table>
<?php                                       } ?>
                                    </span>
                                </article>
<?php                           if($this->basket) { ?>
                                    <article id="orderArticle">
                                        <span>
                                            <?php echo $this->orderstartForm($this->orderstartForm); ?>
                                        </span>
                                    </article>   
<?php                           } ?>
                            </section>
                            <section id="content">
                                <div class="mainTitle" ><br/><?php echo $this->escape($this->placeholder('mainTitle')); ?></div>
                                <?php echo $this->layout()->content; ?>
                            </section>
                        </header>

                        <footer>Footer</footer>
                        <br class="clear" />
                    </section>
                </section>
            </div>
        </section>
    </body>
</html>