<?php 
$this->placeholder('mainTitle')->set('User-Module : Orderdetail');

$module = 'user';
$controller = 'orderdetail';
if($this->authUserRow['roleId']>2) { ?>   
    <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'add'),NULL,TRUE); ?>">
        <img src="/base/images/icons/create.png">
    </a>
<?php } ?>
<table>
    <tr>
        <th><?php echo $this->translate('lbl_product');?></th>
        <th><?php echo $this->translate('lbl_price');?></th>
        <th><?php echo $this->translate('lbl_quantity');?></th>
        <th><?php echo $this->translate('lbl_total');?></th>
    </tr>
<?php if($this->rows) { ?>
<?php   foreach($this->rows as $row) { ?>
            <tr>
                <td><?php echo $row['productId']?></td>
                <td><?php echo $row['price']?></td>
                <td><?php echo $row['quantity']?></td>
                <td><?php echo $row['price']*$row['quantity']?></td>
<?php           if($this->authUserRow['roleId']>2) { ?>                
                    <td>
                        <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'change', 'orderDetailId' => $row['orderDetailId']),NULL,TRUE); ?>">
                            <img src="/base/images/icons/edit.png">
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'delete', 'orderDetailId' => $row['orderDetailId']),NULL,TRUE); ?>" onclick="return confirm('<?php echo $this->translate('lbl_delete'); ?>?')">
                            <img src="/base/images/icons/cross.png">
                        </a>
                    </td>
<?php           } ?>                    
            </tr>
<?php   } ?>            

<?php } else $this->translate('lbl_emptytable'); ?>            
</table>

