<?php
if(is_array($this->products))
    foreach($this->products as $product) { ?>
        <article id="productArticle">
            <span><?php echo isset($product['locale']['title']) ? $product['locale']['title'] : $product['label'];?></span><br>
            <span><?php echo $this->translate('lbl_price').' : '.$product['price'];?></span><br> 
            <a href="/index/detail/id/<?php echo $product['productId']; ?>">Detail</a>
<?php       if(isset($product['productPhotos']) and is_array($product['productPhotos'])) {
                foreach($product['productPhotos'] as $productPhotos) { ?>            
                    <img class="photoImage" src="/uploads/photos/<?php echo $productPhotos['label'];?>" >
<?php               break;
                }
            } ?>
        </article>
<?php } ?>