<?php 
if ($this->userRow['ID_Taal'] == 2){ /*Français */ ?>
    Bonjour <?php echo $this->escape($this->userRow['firstName']); ?>,<br /><br />
    Cliquez sur le lien ci-dessous pour réinitialiser le mot de passe <br /><br />
    <a href="<?php echo $this->escape($this->data['url']); ?>">Cliquer ici</a><br />
   
    <br />
    Cordialement,<br />
    
    Winsol IT Support
<?php 
} else { /*default NL */ ?>
    Beste <?php echo $this->escape($this->userRow['firstName']); ?>,<br /><br />
    Klik op onderstaande link om je paswoord opnieuw in te stellen <br /><br />
    <a href="<?php echo $this->escape($this->data['url']); ?>">Klik hier</a><br />
   
    <br />
    Met vriendelijke groeten,<br />

    Winsol IT Support
<?php } ?>