<?php 
$this->placeholder('mainTitle')->set('Dealer-Module : User');

$module = 'dealer';
$controller = 'user';
?>

<table>
    <tr>
        <th><?php echo $this->translate('lbl_name');?></th>
        <th><?php echo $this->translate('lbl_email');?></th>
        <th><?php echo $this->translate('lbl_role');?></th>
    </tr>
<?php if($this->rows) { ?>
<?php   foreach($this->rows as $row) { ?>
            <tr>
                <td><?php echo $row['name'];?></td>
                <td><?php echo $row['email']?></td>
                <td><?php echo $row['roleId']?></td>
                <td>
                    <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'change', 'userId' => $row['userId']),NULL,TRUE); ?>">
                        <img src="/base/images/icons/edit.png">
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->url(array('module'=> $module,'controller' => $controller, 'action' => 'delete', 'userId' => $row['userId']),NULL,TRUE); ?>" onclick="return confirm('<?php echo $this->translate('lbl_delete'); ?>?')">
                        <img src="/base/images/icons/cross.png">
                    </a>
                </td>
            </tr>
<?php   } ?>            

<?php } else $this->translate('lbl_emptytable'); ?>            
</table>

